swagger: '2.0'
info:
  title: Local Management APIs activations installers API
  version: v1
servers:
- url: https://edge-host-ip:5080
schemes:
- http
- https
consumes:
- application/json
produces:
- application/json
tags:
- name: installers
  x-displayName: Installers
paths:
  /v1/installers/spectro:
    post:
      operationId: v1SpectrospectroInstallerCreate
      parameters:
      - in: body
        name: body
        schema:
          $ref: '#/definitions/v1SpectroInstallerInputEntity'
      - description: A project UID is required for project-scoped resources and should be omitted when targeting tenant-scoped resources
        in: header
        name: ProjectUid
        type: string
      responses:
        '201':
          description: Created successfully
          headers:
            AuditUid:
              description: Audit uid for the request
              type: string
          schema:
            $ref: '#/definitions/v1Uid'
      security:
      - ApiKey: []
      - Authorization: []
      summary: Creates the spectro installer
      tags:
      - installers
definitions:
  v1ObjectMetaInputEntity:
    description: ObjectMeta input entity for object creation
    properties:
      annotations:
        additionalProperties:
          type: string
        description: 'Annotations is an unstructured key value map stored with a resource that may be set by external tools to store and retrieve arbitrary metadata. They are not queryable and should be preserved when modifying objects. More info: http://kubernetes.io/docs/user-guide/annotations'
        type: object
      labels:
        additionalProperties:
          type: string
        description: 'Map of string keys and values that can be used to organize and categorize (scope and select) objects. May match selectors of replication controllers and services. More info: http://kubernetes.io/docs/user-guide/labels'
        type: object
      name:
        description: 'Name must be unique within a namespace. Is required when creating resources, although some resources may allow a client to request the generation of an appropriate name automatically. Name is primarily intended for creation idempotence and configuration definition. Cannot be updated. More info: http://kubernetes.io/docs/user-guide/identifiers#names'
        type: string
    type: object
  v1SpectroInstallerInputEntity:
    description: Spectro installer entity for create
    properties:
      metadata:
        $ref: '#/definitions/v1ObjectMetaInputEntity'
    type: object
  v1Uid:
    properties:
      uid:
        type: string
    required:
    - uid
    type: object
securityDefinitions:
  Authorization:
    description: JWT authorization token obtained using /v1/users/default/login API
    type: apiKey
    name: Authorization
    in: header
