openapi: 3.2.0
info:
  title: Local Management Ping API
  version: v1
servers:
- url: https://edge-host-ip:5080
tags:
- name: Ping
  x-displayName: Ping
paths:
  /v1/ping:
    get:
      tags:
      - Ping
      summary: Ping Service
      operationId: V1Ping
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/v1Ping'
        default:
          description: generic error response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/apiError'
      security:
      - Authorization: []
components:
  schemas:
    apiError:
      type: string
    v1Ping:
      type: object
      properties:
        msg:
          type: string
  securitySchemes:
    Authorization:
      description: JWT authorization token obtained using /v1/users/default/login API
      type: apiKey
      name: Authorization
      in: header
