swagger: '2.0'
info:
  title: Local Management APIs activations spcPolicies API
  version: v1
servers:
- url: https://edge-host-ip:5080
schemes:
- http
- https
consumes:
- application/json
produces:
- application/json
tags:
- name: spcPolicies
  x-displayName: Spc Policies
paths:
  /v1/spcPolicies/maintenance:
    post:
      operationId: V1SpcPoliciesMaintenanceCreate
      parameters:
      - in: body
        name: body
        schema:
          $ref: '#/definitions/v1SpcPolicyEntity'
      - description: A project UID is required for project-scoped resources and should be omitted when targeting tenant-scoped resources
        in: header
        name: ProjectUid
        type: string
      responses:
        '201':
          description: Created successfully
          headers:
            AuditUid:
              description: Audit uid for the request
              type: string
          schema:
            $ref: '#/definitions/v1Uid'
      security:
      - ApiKey: []
      - Authorization: []
      summary: Create a new maintenance policy
      tags:
      - spcPolicies
  /v1/spcPolicies/maintenance/{uid}:
    parameters:
    - description: Policy uid
      in: path
      name: uid
      required: true
      type: string
    get:
      operationId: V1SpcPoliciesMaintenanceUidGet
      parameters:
      - description: A project UID is required for project-scoped resources and should be omitted when targeting tenant-scoped resources
        in: header
        name: ProjectUid
        type: string
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/v1SpcPolicyEntity'
      security:
      - ApiKey: []
      - Authorization: []
      summary: Returns the specified maintenance policy
      tags:
      - spcPolicies
    put:
      operationId: V1SpcPoliciesMaintenanceUidUpdate
      parameters:
      - in: body
        name: body
        schema:
          $ref: '#/definitions/v1SpcPolicyEntity'
      - description: A project UID is required for project-scoped resources and should be omitted when targeting tenant-scoped resources
        in: header
        name: ProjectUid
        type: string
      responses:
        '204':
          description: The resource was updated successfully
      security:
      - ApiKey: []
      - Authorization: []
      summary: Updates the specified maintenance policy
      tags:
      - spcPolicies
  /v1/spcPolicies/tags:
    get:
      operationId: V1SpcPoliciesTagsGet
      parameters:
      - description: A project UID is required for project-scoped resources and should be omitted when targeting tenant-scoped resources
        in: header
        name: ProjectUid
        type: string
      responses:
        '200':
          description: An array of spc policy tags
          schema:
            $ref: '#/definitions/v1SpcPolicyTags'
      security:
      - ApiKey: []
      - Authorization: []
      summary: Retrieves a list of spc policy tags
      tags:
      - spcPolicies
  /v1/spcPolicies/{policyType}/validate/name:
    parameters:
    - description: Spc policy type
      in: path
      name: policyType
      required: true
      type: string
    get:
      operationId: V1SpcPoliciesValidateName
      parameters:
      - description: Spc policy name
        in: query
        name: name
        type: string
      - description: A project UID is required for project-scoped resources and should be omitted when targeting tenant-scoped resources
        in: header
        name: ProjectUid
        type: string
      responses:
        '204':
          description: Ok response without content
          headers:
            AuditUid:
              description: Audit uid for the request
              type: string
      security:
      - ApiKey: []
      - Authorization: []
      summary: Validates the spc policy name
      tags:
      - spcPolicies
  /v1/spcPolicies/{uid}:
    parameters:
    - in: path
      name: uid
      required: true
      type: string
    delete:
      operationId: V1SpcPoliciesUidDelete
      parameters:
      - description: A project UID is required for project-scoped resources and should be omitted when targeting tenant-scoped resources
        in: header
        name: ProjectUid
        type: string
      responses:
        '204':
          description: The resource was deleted successfully
      security:
      - ApiKey: []
      - Authorization: []
      summary: Delete a policy by uid
      tags:
      - spcPolicies
definitions:
  v1SpcPolicyEntity:
    description: Policy entity information
    properties:
      metadata:
        $ref: '#/definitions/v1ObjectMeta'
      spec:
        $ref: '#/definitions/v1SpcPolicySpec'
    type: object
  v1Time:
    description: Time is a wrapper around time.Time which supports correct marshaling to YAML and JSON.  Wrappers are provided for many of the factory methods that the time package offers.
    format: date-time
    type: string
  v1Schedule:
    description: Information about a schedule for the policy
    properties:
      durationHrs:
        description: Specifies the time window in hours during which the system is allowed to start upgrades on eligible clusters. Actual upgrade completion may vary due to cluster-specific factors like bandwidth, capacity, or environment.
        maximum: 24
        minimum: 1
        type: integer
      name:
        description: Name of the upgrade schedule
        type: string
      startCron:
        description: Cron expression for the start time of the schedule
        type: string
    required:
    - durationHrs
    - startCron
    - name
    type: object
  v1Uid:
    properties:
      uid:
        type: string
    required:
    - uid
    type: object
  v1SpcPolicySpec:
    description: Policy specification
    properties:
      schedules:
        items:
          $ref: '#/definitions/v1Schedule'
        type: array
    type: object
  v1SpcPolicyTags:
    description: Spc policy tags response
    properties:
      tags:
        description: Array of spc policy tags
        items:
          type: string
        type: array
    type: object
  v1ObjectMeta:
    description: ObjectMeta is metadata that all persisted resources must have, which includes all objects users must create.
    properties:
      annotations:
        additionalProperties:
          type: string
        description: 'Annotations is an unstructured key value map stored with a resource that may be set by external tools to store and retrieve arbitrary metadata. They are not queryable and should be preserved when modifying objects. More info: http://kubernetes.io/docs/user-guide/annotations'
        type: object
      creationTimestamp:
        $ref: '#/definitions/v1Time'
        description: 'CreationTimestamp is a timestamp representing the server time when this object was created. It is not guaranteed to be set in happens-before order across separate operations. Clients may not set this value. It is represented in RFC3339 form and is in UTC.


          Populated by the system. Read-only. Null for lists. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#metadata'
      deletionTimestamp:
        $ref: '#/definitions/v1Time'
        description: 'DeletionTimestamp is RFC 3339 date and time at which this resource will be deleted. This field is set by the server when a graceful deletion is requested by the user, and is not directly settable by a client. The resource is expected to be deleted (no longer visible from resource lists, and not reachable by name) after the time in this field, once the finalizers list is empty. As long as the finalizers list contains items, deletion is blocked. Once the deletionTimestamp is set, this value may not be unset or be set further into the future, although it may be shortened or the resource may be deleted prior to this time. For example, a user may request that a pod is deleted in 30 seconds. The Kubelet will react by sending a graceful termination signal to the containers in the pod. After that 30 seconds, the Kubelet will send a hard termination signal (SIGKILL) to the container and after cleanup, remove the pod from the API. In the presence of network partitions, this object may still exist after this timestamp, until an administrator or automated process can determine the resource is fully terminated. If not set, graceful deletion of the object has not been requested.


          Populated by the system when a graceful deletion is requested. Read-only. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#metadata'
      labels:
        additionalProperties:
          type: string
        description: 'Map of string keys and values that can be used to organize and categorize (scope and select) objects. May match selectors of replication controllers and services. More info: http://kubernetes.io/docs/user-guide/labels'
        type: object
      lastModifiedTimestamp:
        $ref: '#/definitions/v1Time'
        description: 'LastModifiedTimestamp is a timestamp representing the server time when this object was last modified. It is not guaranteed to be set in happens-before order across separate operations. Clients may not set this value. It is represented in RFC3339 form and is in UTC.


          Populated by the system. Read-only. Null for lists. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#metadata'
      name:
        description: 'Name must be unique within a namespace. Is required when creating resources, although some resources may allow a client to request the generation of an appropriate name automatically. Name is primarily intended for creation idempotence and configuration definition. Cannot be updated. More info: http://kubernetes.io/docs/user-guide/identifiers#names'
        type: string
      uid:
        description: 'UID is the unique in time and space value for this object. It is typically generated by the server on successful creation of a resource and is not allowed to change on PUT operations.


          Populated by the system. Read-only. More info: http://kubernetes.io/docs/user-guide/identifiers#uids'
        type: string
    type: object
securityDefinitions:
  Authorization:
    description: JWT authorization token obtained using /v1/users/default/login API
    type: apiKey
    name: Authorization
    in: header
