swagger: '2.0'
info:
  title: Local Management APIs activations services API
  version: v1
servers:
- url: https://edge-host-ip:5080
schemes:
- http
- https
consumes:
- application/json
produces:
- application/json
tags:
- name: services
  x-displayName: Services
paths:
  /v1/services/{serviceName}/version:
    get:
      operationId: v1ServiceVersionGet
      parameters:
      - description: service name
        enum:
        - ally
        - jet
        - palette
        - ambit
        - ally-lite
        - palette-lite
        - crony
        - tick
        - edge
        - lodge
        - level
        - edgeconfig
        - firth
        - stylus
        - provider-k3s
        - provider-kubeadm
        - provider-rke2
        - provider-nodeadm
        - provider-canonical
        in: path
        name: serviceName
        required: true
        type: string
      - description: spectro cluster uid
        in: query
        name: clusterUid
        type: string
      - description: edge host uid
        in: query
        name: edgeHostUid
        type: string
      - description: A project UID is required for project-scoped resources and should be omitted when targeting tenant-scoped resources
        in: header
        name: ProjectUid
        type: string
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/v1ServiceVersion'
      security:
      - ApiKey: []
      - Authorization: []
      summary: Returns a latest version for a given service name
      tags:
      - services
  /v1/services/{serviceName}/versions/{version}/manifest:
    get:
      operationId: v1ServiceManifestGet
      parameters:
      - description: service name
        enum:
        - ally
        - jet
        - palette
        - ambit
        - ally-lite
        - palette-lite
        - crony
        - tick
        - edge
        - lodge
        - level
        - edgeconfig
        - firth
        - stylus
        - provider-k3s
        - provider-kubeadm
        - provider-rke2
        - provider-nodeadm
        - provider-canonical
        in: path
        name: serviceName
        required: true
        type: string
      - description: service version
        in: path
        name: version
        required: true
        type: string
      - description: action type
        enum:
        - apply
        - delete
        - resources
        in: query
        name: action
        required: true
        type: string
      - description: resource file name
        in: query
        name: resourceFilename
        type: string
      - description: spectro cluster uid
        in: query
        name: clusterUid
        type: string
      - description: edge host uid
        in: query
        name: edgeHostUid
        type: string
      - description: A project UID is required for project-scoped resources and should be omitted when targeting tenant-scoped resources
        in: header
        name: ProjectUid
        type: string
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/v1ServiceManifest'
      security:
      - ApiKey: []
      - Authorization: []
      summary: Returns a service manifest for a given service name and version
      tags:
      - services
definitions:
  v1Time:
    description: Time is a wrapper around time.Time which supports correct marshaling to YAML and JSON.  Wrappers are provided for many of the factory methods that the time package offers.
    format: date-time
    type: string
  v1ServiceManifestSpec:
    properties:
      manifests:
        items:
          $ref: '#/definitions/v1GitRepoFileContent'
        type: array
        uniqueItems: true
      name:
        type: string
      version:
        type: string
    type: object
  v1ServiceVersionSpec:
    properties:
      latestVersion:
        $ref: '#/definitions/v1GitRepoFileContent'
      name:
        type: string
    type: object
  v1GitRepoFileContent:
    properties:
      content:
        type: string
      name:
        type: string
      path:
        type: string
      repoName:
        type: string
      sha:
        type: string
    type: object
  v1ServiceVersion:
    description: Service version information
    properties:
      apiVersion:
        type: string
      kind:
        type: string
      metadata:
        $ref: '#/definitions/v1ObjectMeta'
      spec:
        $ref: '#/definitions/v1ServiceVersionSpec'
    type: object
  v1ObjectMeta:
    description: ObjectMeta is metadata that all persisted resources must have, which includes all objects users must create.
    properties:
      annotations:
        additionalProperties:
          type: string
        description: 'Annotations is an unstructured key value map stored with a resource that may be set by external tools to store and retrieve arbitrary metadata. They are not queryable and should be preserved when modifying objects. More info: http://kubernetes.io/docs/user-guide/annotations'
        type: object
      creationTimestamp:
        $ref: '#/definitions/v1Time'
        description: 'CreationTimestamp is a timestamp representing the server time when this object was created. It is not guaranteed to be set in happens-before order across separate operations. Clients may not set this value. It is represented in RFC3339 form and is in UTC.


          Populated by the system. Read-only. Null for lists. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#metadata'
      deletionTimestamp:
        $ref: '#/definitions/v1Time'
        description: 'DeletionTimestamp is RFC 3339 date and time at which this resource will be deleted. This field is set by the server when a graceful deletion is requested by the user, and is not directly settable by a client. The resource is expected to be deleted (no longer visible from resource lists, and not reachable by name) after the time in this field, once the finalizers list is empty. As long as the finalizers list contains items, deletion is blocked. Once the deletionTimestamp is set, this value may not be unset or be set further into the future, although it may be shortened or the resource may be deleted prior to this time. For example, a user may request that a pod is deleted in 30 seconds. The Kubelet will react by sending a graceful termination signal to the containers in the pod. After that 30 seconds, the Kubelet will send a hard termination signal (SIGKILL) to the container and after cleanup, remove the pod from the API. In the presence of network partitions, this object may still exist after this timestamp, until an administrator or automated process can determine the resource is fully terminated. If not set, graceful deletion of the object has not been requested.


          Populated by the system when a graceful deletion is requested. Read-only. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#metadata'
      labels:
        additionalProperties:
          type: string
        description: 'Map of string keys and values that can be used to organize and categorize (scope and select) objects. May match selectors of replication controllers and services. More info: http://kubernetes.io/docs/user-guide/labels'
        type: object
      lastModifiedTimestamp:
        $ref: '#/definitions/v1Time'
        description: 'LastModifiedTimestamp is a timestamp representing the server time when this object was last modified. It is not guaranteed to be set in happens-before order across separate operations. Clients may not set this value. It is represented in RFC3339 form and is in UTC.


          Populated by the system. Read-only. Null for lists. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#metadata'
      name:
        description: 'Name must be unique within a namespace. Is required when creating resources, although some resources may allow a client to request the generation of an appropriate name automatically. Name is primarily intended for creation idempotence and configuration definition. Cannot be updated. More info: http://kubernetes.io/docs/user-guide/identifiers#names'
        type: string
      uid:
        description: 'UID is the unique in time and space value for this object. It is typically generated by the server on successful creation of a resource and is not allowed to change on PUT operations.


          Populated by the system. Read-only. More info: http://kubernetes.io/docs/user-guide/identifiers#uids'
        type: string
    type: object
  v1ServiceManifest:
    description: Service manifest information
    properties:
      apiVersion:
        type: string
      kind:
        type: string
      metadata:
        $ref: '#/definitions/v1ObjectMeta'
      spec:
        $ref: '#/definitions/v1ServiceManifestSpec'
    type: object
securityDefinitions:
  Authorization:
    description: JWT authorization token obtained using /v1/users/default/login API
    type: apiKey
    name: Authorization
    in: header
